name: pyrcel
channels:
    - conda-forge
dependencies:
    - python==3.10
    - assimulo==3.6
    - pandas
    - pyyaml
    - scipy
    - numba
    - numpy<2.2
    - xarray
    - numpydoc
    - ipython
    - sphinx
    - sphinx_rtd_theme